# 微服务配置

# TCP = 0,
# REDIS = 1,
# NATS = 2,
# MQTT = 3,
# GRPC = 4,
# RMQ = 5,
# KAFKA = 6

# 服务端 -- 服务端配置
microserviceService:
  transport: 0
  options:
    host: 0.0.0.0
    port: 5010

# 微服务 -- 客户端配置
# microserviceClients.key 主要用于注入 @Inject(name)
microserviceClients:
  FISHER_MAN_SERVICE:
    transport: 0
    options:
      host: localhost
      port: 5111 # 微服务的端口，注意不是启动的端口，是通信的端口，与apps中的microserviceService中的端口对应
  USER_CENTER_SERVICE:
    transport: 0
    options:
      host: localhost
      port: 5112 # # 微服务的端口，注意不是启动的端口，是通信的端口，与apps中的microserviceService中的端口对应