# jwt配置
jwt:
  secret: nestservicebugdr # 加密串，生产环境必须更改
  expiresIn: 36000s # 过期时间

# 权限配置
permission:
  # 权限动作集
  actions: ['create', 'delete', 'update', 'query']
  # 权限模块
  apps:
    # 账户模块

# 权限模块名称
permissionNames:
  create: 创建
  delete: 删除
  update: 更新
  query: 查询
  account: 账号管理
  account.adminRole: 管理员角色
  account.admin: 管理员账号
  account.user: 用户账号
  infos: 信息管理
  infos.category: 信息分类
  infos.article: 文章管理
  system: 系统设置
  system.files: 文件管理