# jwt配置
jwt:
  secret: nestservicebugdr # 加密串，生产环境必须更改
  expiresIn: 7200s # 过期时间为2个小时

# 权限配置
permission:
  # 权限动作集
  actions: [create, delete, update, query]
  # 服务模块
  apps:
    # 账户模块
    user-center-service: [app, login-record, settings, token, user, user-info, role]
    # 剩余模块后续再加入

# 权限模块名称
permissionNames:
  create: 创建
  delete: 删除
  update: 更新
  query: 查询
  user-center-service: 摸鱼君统一用户中心
  user-center-service.app: 用户中心-应用程序
  user-center-service.login-record: 用户中心-用户登录记录
  user-center-service.settings: 用户中心-系统设置
  user-center-service.token: 用户中心-token管理
  user-center-service.user: 用户中心-用户管理
  user-center-service.user.info: 用户中心-用户信息