# jwt配置
jwt:
  secret: nestservicebugdr # 加密串，生产环境必须更改
  expiresIn: 36000s # 过期时间

# 权限配置
permission:
  # 权限动作集
  actions: [create, delete, update, query]
  # 权限模块
  apps:
    # 账户模块
    user-center-service: [app, login, settings, token, user, user-info]
    # 剩余模块后续再加入

# 权限模块名称
permissionNames:
  create: 创建
  delete: 删除
  update: 更新
  query: 查询
  user-center-service: 摸鱼君统一用户中心
  user-center-service.app: 用户中心程序
  user-center-service.login: 登陆
  account.user: 用户账号
  infos: 信息管理
  infos.category: 信息分类
  infos.article: 文章管理
  system: 系统设置
  system.files: 文件管理
